#!/usr/bin/env node
// epochs.mjs: refresh public/projects/js/orbit/epochs.js, the difficulty-adjustment
// table NOSTR ORBIT uses to turn a timestamp into a block height (one row per
// adjustment, [height, timestamp of that block]). The page also fetches newer
// rows live, so a stale table only costs accuracy for the newest fortnights.
import fs from 'node:fs';
const OUT = new URL('../public/projects/js/orbit/epochs.js', import.meta.url).pathname;
const rows = await (await fetch('https://mempool.space/api/v1/mining/difficulty-adjustments')).json();
const table = rows.map(([ts, h]) => [h, ts]).sort((a, b) => a[0] - b[0]);
let gaps = 0;
for (let i = 1; i < table.length; i++) {
  if (table[i][0] % 2016 || table[i][1] <= table[i - 1][1]) throw new Error('bad row ' + i);
  if (table[i][0] !== table[i - 1][0] + 2016) gaps++;
}
fs.writeFileSync(OUT, `// epochs.js: every difficulty adjustment since genesis as [height, timestamp of that block].\n// Generated by tools/epochs.mjs from mempool.space; the page merges newer rows live.\nexport const EPOCHS = [\n${table.map(r => `[${r[0]},${r[1]}]`).join(',\n')}\n];\n`);
console.log(`${table.length} rows, ${gaps} gaps (2009 epochs without a change), last ${table.at(-1)}`);
